
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: mtuser
      RABBITMQ_DEFAULT_PASS: mt2024
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
  your_service:
    image: your_service_image
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - rabbitmq_network
networks:
  rabbitmq_network:
volumes:
  rabbitmq_data:
